<a href="https://colab.research.google.com/github/pchodon/Amegashita/blob/Feature-Integration/%20TF%20port%20ready.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import tensorflow as tf
import numpy as np
import tensorflow as tf
import numpy as np
import pandas as pd
import sys


No_of_records = 4
Parameters = 4
No_of_elements = 10

x1 = tf.zeros([No_of_records,Parameters,No_of_elements])
#x1 = tf.zeros([3,2,5])

x2 = tf.zeros([0])

print(sys.getsizeof(x1)) 

print("Test")
ta = tf.TensorArray(tf.float32, size=sys.getsizeof(x1), dynamic_size=True, clear_after_read=False)

np.b =np.zeros((No_of_records,Parameters,No_of_elements))


  
b = ([[[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

count = 0
count1 = 0
for count in range(0,5):
  print(b[0][0][count])
print("-----------------------------------------------")
for count in range(0,5):
  print(b[1][0][count])
print("-----------------------------------------------")
for count in range(0,5):
  print(b[2][0][count]),
print("-----------------------------------------------")
for count in range(0,5):
  print(b[0][1][count]),
print("-----------------------------------------------")
for count in range(0,5):
  print(b[1][1][count]),
print("-----------------------------------------------")
for count in range(0,5):
  print(b[2][1][count])

print("-----------------------------------------------")

rank_3_tensor= tf.convert_to_tensor(b, dtype=tf.float32)
print(rank_3_tensor)

for count in range(0,5):
  print(rank_3_tensor[0][0][count])
print("-----------------------------------------------")
for count in range(0,5):
  print(rank_3_tensor[1][0][count])
print("-----------------------------------------------")
for count in range(0,5):
  print(rank_3_tensor[2][0][count]),
print("-----------------------------------------------")
for count in range(0,5):
  print(rank_3_tensor[0][1][count]),
print("-----------------------------------------------")
for count in range(0,5):
  print(rank_3_tensor[1][1][count]),
print("-----------------------------------------------")
for count in range(0,5):
  print(rank_3_tensor[2][1][count])

print("-----------------------------------------------")


184
Test
0
1
2
3
4
-----------------------------------------------
10
11
12
13
14
-----------------------------------------------
20
21
22
23
24
-----------------------------------------------
5
6
7
8
9
-----------------------------------------------
15
16
17
18
19
-----------------------------------------------
25
26
27
28
29
-----------------------------------------------
tf.Tensor(
[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]]

 [[10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]]

 [[20. 21. 22. 23. 24.]
  [25. 26. 27. 28. 29.]]], shape=(3, 2, 5), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(4.0, shape=(), dtype=float32)
-----------------------------------------------
tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor(11.0, shape=(), dtype=float32)
tf.Tensor(12.0, shape=(), dtype=float32)
tf.Tensor(13.0, shape=(), dtype=float32)
tf.Tensor(14.0, s