In [5]:
from google.colab import drive
drive.mount('/content/drive')

import multiprocessing
import time
from csv import reader
from google.colab import files
import pandas as pd
import threading
import os
import tensorflow as tf
import numpy as np
import sys
import matplotlib.pyplot as plt

rank_2_tensor = tf.constant([[0*10]*10]*10, dtype=tf.float16)
msg = [0,1]

def Visual_Tracer(parent_conn,child_conn,msg):
  data = []
  with open('/content/drive/MyDrive/square1.csv', 'r') as data:
    df_sensory_2 = pd.read_csv(data)
    print(df_sensory_2)
    return()

def Visual_field(parent_conn,child_conn,msg):
  while(1):
    time.sleep(10)
    print(rank_2_tensor)



if __name__ == "__main__":
  ##print("System Starting......")

  parent_conn, child_conn = multiprocessing.Pipe()

  p1 = multiprocessing.Process(target=Visual_field, args=(parent_conn,child_conn,msg))
  p2 = multiprocessing.Process(target=Visual_Tracer, args=(parent_conn,child_conn,msg))


  p1.start()
  time.sleep(1)
  p2.start()

  time.sleep(100)
  p2.join()
  p1.join()
  time.sleep(20)
  print("Starting new episode")
#333444












Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
    0
0   0
1   0
2   0
3   0
4   0
.. ..
84  0
85  0
86  0
87  0
88  0

[89 rows x 1 columns]
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float16)


Process Process-5:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-5-dcdb6be1b9c9>", line 28, in Visual_field
    time.sleep(10)
KeyboardInterrupt


KeyboardInterrupt: ignored