<a href="https://colab.research.google.com/github/pchodon/Amegashita/blob/basecode/TF_ref5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import tensorflow as tf
import numpy as np

episode = 4 # Episode 10:0,0:10,5:5
path = 4    # 0 time / 1 sensor 1 / 2 sensor 2 / 2 learning
spike = 10   # 0 & 1 values


import tensorflow as tf
import numpy as np



x1 = tf.zeros([3,2,5])

max_loop = tf.shape(x1)[0]

max_loop = tf.shape(x1)[0]

x1 = tf.TensorArray(dtype=tf.float32, size= max_loop + 1,
                                             dynamic_size=False, clear_after_read = False,infer_shape=True)
test = [0,0]*5


test[0] = tf.Variable(np.array([0, 1, 2, 3, 4], dtype = np.float32))
test[1] = tf.Variable(np.array([6,7,8,9,10], dtype = np.float32))
test[2] = tf.Variable(np.array([11,12,13,14,15], dtype = np.float32))
test[3] = tf.Variable(np.array([15, 16, 17, 18, 19], dtype = np.float32))
test[4] = tf.Variable(np.array([20, 21, 22, 23, 24], dtype = np.float32))
test[4] = tf.Variable(np.array([24, 25, 26, 27, 28], dtype = np.float32))


for count in range(0,1):
  for count1 in range(0,5):
     x1 = x1.write(count,tf.Variable(tf.Variable(test[count1], dtype = np.float32), dtype = np.float32))
     print(x1.read(count,count1).numpy())




print("test")


[0. 1. 2. 3. 4.]
[ 6.  7.  8.  9. 10.]
[11. 12. 13. 14. 15.]
[15. 16. 17. 18. 19.]
[24. 25. 26. 27. 28.]
test
